language: node_js
node_js:
  - 14

services:
  - docker


script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed tolu1292/udagram-api-feed:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user tolu1292/udagram-api-user:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend tolu1292/udagram-frontend:v1

  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy tolu1292/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bitcliff/udagram-api-feed:v1
  - docker push bitcliff/udagram-api-user:v1
  - docker push bitcliff/udagram-frontend:v1
  - docker push bitcliff/reverseproxy:v1