apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-reverseproxy
  name: backend-reverseproxy
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    service: backend-reverseproxy