apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user 
    spec:
      containers:
      - name: backed-user
        image: docker.io/tolu1292/udagram-api-user:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m