apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-reverseproxy
  
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-reverseproxy 
    spec:
      containers:
      - name: backed-reverseproxy
        image: docker.io/tolu1292/udagram-reverseproxy:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m