apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: udagram-frontend 
    spec:
      containers:
      - name: udagram-frontend
        image: docker.io/tolu1292/udagram-frontend:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m